package moonhyuk.lee.resultmap.generator;

import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;

/**
 * Mapper 인터페이스 생성 전담 클래스
 */
class MapperInterfaceGenerator {

    private final ProcessingEnvironment processingEnv;
    private final Messager messager;

    public MapperInterfaceGenerator(ProcessingEnvironment processingEnv, Messager messager) {
        this.processingEnv = processingEnv;
        this.messager = messager;
    }

    /**
     * AutoGeneratedMapper 인터페이스 생성
     */
    public String generateMapperInterface() {
        return """
            package mapper;

            import org.apache.ibatis.annotations.Mapper;

            @Mapper
            public interface AutoGeneratedMapper {
                // Add your mapper methods here
            }
            """;
    }
}